const pics = [
  "main",
  "users",
  "contacts",
  "complaint",
  "workplace-1",
  "workplace-2",
  "workplace-3",
  "workplace-4",
  "aim-1",
  "aim-2",
  "aim-3",
  "data-1",
  "data-2",
  "set-1",
  "set-2",
  "term-1",
  "term-2",
  "tools-auto-1",
  "tools-auto-2",
  "tools-auto-3",
  "tools-auto-4",
  "tools-auto-5",
  "tools-auto-6",
  "tools-auto-7",
  "tools-whitelist",
  "tools-blacklist",
  "tools-single-del",
  "tools-task",
  "tools-ticket",
  "tools-user",
  "tools-grouping-1",
  "tools-grouping-2",
  "tools-mass-1",
  "tools-mass-2",
  "tools-sop-1",
  "tools-sop-2",
  "tools-sop-3",
  "tools-sop-4",
  "tools-sop-5",
  "tools-sop-6",
  "tools-sop-7",
  "tools-sop-8",
  "tools-sop-9",
  "tools-sop-10",
  "tools-sop-11",
  "tools-sop-12",
].map((c, idx) => {
  const url = `/images/projects/jojo-luban/${c}.${idx > 0 ? "jpg" : "png"}`;

  return {
    url,
    thumbnail: url,
    ...(idx > 0 ? { width: 1500, height: 845 } : { width: 1306, height: 717 }),
  };
});

export default pics;
