import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout";

import { getSortedPostsData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return { props: { allPostsData } };
}

const Home: NextPage = ({ allPostsData }: any) => {
  return (
    <Layout home>
      <div>
        {/* <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}

        <main>
          <section>
            <h2>Blog</h2>
            <ul>
              {allPostsData.map(({ id, date, title }: any) => (
                <li key={id}>
                  <Link href={`/posts/${id}`}>
                    <a>{title}</a>
                  </Link>
                  <br />
                  {date}
                </li>
              ))}
            </ul>
          </section>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
