export default [
  {
    key: "1",
    name: "鲁班系统",
    labels: ["react", "electron", "nodejs"],
    icons: ["devicon:react", "devicon:electron", "devicon:nodejs"],
    desc: "包含桌面端与WEB端，定位于关注精细化运营、高效运营支撑。主要支撑课程顾问、班主任老师对客户转化、社群运营的诉求，协助一线老师完成销售、运营目标。",
  },
  {
    key: "2",
    name: "工单系统",
    labels: ["react", "antd", "antd-mobile"],
    icons: ["devicon:react", "devicon:antdesign", "antdmobile"],
    desc: "包含WEB端、H5（微信客户端、钉钉管理端）。主要为解决公司内部业务上需要通过工单的方式进行流转的工作流程，降低在使用三方记录工具与人力占用的成本。",
  },
  {
    key: "3",
    name: "基础权限平台",
    labels: ["react", "antd", "qiankun"],
    icons: ["devicon:react", "devicon:antdesign", "devicon:antdesign"],
    desc: "微前端架构，内部中台系统、三方应用、员工部门及权限相关管理系统。",
  },
  {
    key: "4",
    name: "仿真镜像平台",
    labels: ["react", "antd"],
    icons: ["devicon:react", "devicon:antdesign"],
    desc: "用于克隆线上产品（如淘宝、天猫）环境的真实数据后，在镜像环境中能引流更多流量做更多真实的验证，包括核对监控等。",
  },
  {
    key: "5",
    name: "倍事达管理系统",
    labels: ["react", "antd"],
    icons: ["devicon:react", "devicon:antdesign"],
    desc: "一个PCO有害生物防治行业SaaS软件系统，主要服务于食品行业、连锁餐厅等PCO虫控企业用户。",
  },
  {
    key: "6",
    name: "幼学空间",
    labels: ["react", "antd", "antd-mobile"],
    icons: ["devicon:react", "devicon:antdesign", "antdmobile"],
    desc: "一个集资源组织、专家、园长、后台管理及移动H5五个端所组成的中大型项目。主要用于管理幼儿教师资格认证、培训、幼儿教育、教育资源维护等功能。",
  },
  {
    key: "7",
    name: "青少年毒品预防教育平台",
    url: "http://www.jxjd627.com",
    labels: ["jquery", "requirejs"],
    icons: ["devicon:jquery", "logos:require"],
    desc: "针对青少年毒品知识的宣传与教育，加强青少年对毒品危害的认识。其方式有文章、视频、及毒品知识测试。",
  },
  {
    key: "8",
    name: "营养健康专家端管理应用",
    labels: ["react", "redux", "sass"],
    icons: ["devicon:react", "devicon:redux", "devicon:sass"],
    desc: "用于营养专家对客户咨询支持以前专家对营养资讯及食谱和关注者的管理。",
  },
  {
    key: "9",
    name: "DSP广告投放平台",
    labels: ["angular", "echarts"],
    icons: ["devicon:angular", "simple-icons:apacheecharts"],
    desc: "用于广告投放管理包括了分时、资源、媒体、受众等报表以及创意、订单、用户等子系统，容括了广告投放等系列功能，便于使用者全面掌握当前自己的所有情况。",
  },
];
