export const list = [
  {
    id: 0,
    title: "测试示例Ⅰ",
    name: "沐雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: false,
  },
  {
    id: 1,
    title: "测试示例Ⅱ",
    name: "清风",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: false,
  },
  {
    id: 2,
    title: "测试示例Ⅲ",
    name: "风沐",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: true,
  },
  {
    id: 3,
    title: "测试示例Ⅳ",
    name: "清雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: false,
  },
  {
    id: 4,
    title: "测试示例Ⅴ",
    name: "清风沐",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: true,
  },
  {
    id: 5,
    title: "测试示例Ⅵ",
    name: "清风雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: true,
  },
  {
    id: 6,
    title: "测试示例Ⅶ",
    name: "清沐雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: false,
  },
  {
    id: 7,
    title: "测试示例Ⅷ",
    name: "风沐雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: true,
  },
  {
    id: 8,
    title: "测试示例Ⅸ",
    name: "风雪",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: true,
  },
  {
    id: 9,
    title: "测试示例Ⅹ",
    name: "清沐",
    bDate: "2016-12-31",
    eDate: "2017-03-04",
    isTest: false,
  },
];

export const data = [
  {
    id: "0",
    range: [0, 0],
    name: "您家的饮食口味是什么？（最多选择两项）",
    answer: [
      {
        id: "0",
        mark: "A",
        content: "清淡",
        score: "1",
      },
      {
        id: "1",
        mark: "B",
        content: "适中",
        score: "2",
      },
      {
        id: "2",
        mark: "C",
        content: "喜甜食",
        score: "3",
      },
      {
        id: "3",
        mark: "D",
        content: "酸辣",
        score: "4",
      },
      {
        id: "4",
        mark: "E",
        content: "咸",
        score: "5",
      },
      {
        id: "5",
        mark: "F",
        content: "肥腻",
        score: "6",
      },
    ],
  },
  {
    id: "1",
    range: [1, 1],
    name: "您认为早餐对孩子重要吗？",
    answer: [
      {
        id: "0",
        mark: "A",
        content: "不重要",
        score: "1",
      },
      {
        id: "1",
        mark: "B",
        content: "一般",
        score: "2",
      },
      {
        id: "2",
        mark: "C",
        content: "重要",
        score: "3",
      },
      {
        id: "3",
        mark: "D",
        content: "非常重要",
        score: "4",
      },
    ],
  },
  {
    id: "2",
    range: [2, 2],
    name: "早餐的渠道来源是？",
    answer: [
      {
        id: "0",
        mark: "A",
        content: "路边摊",
        score: "1",
      },
      {
        id: "1",
        mark: "B",
        content: "小餐馆",
        score: "2",
      },
      {
        id: "2",
        mark: "C",
        content: "商店购买",
        score: "3",
      },
      {
        id: "2",
        mark: "D",
        content: "家里吃",
        score: "4",
      },
      {
        id: "3",
        mark: "E",
        content: "学校吃",
        score: "5",
      },
    ],
  },
  {
    id: "3",
    range: [0, 1],
    name: "早餐的种类选择是？",
    answer: [
      {
        id: "0",
        mark: "A",
        content: "油炸类",
        score: "1",
      },
      {
        id: "1",
        mark: "B",
        content: "方便面、速食品",
        score: "2",
      },
      {
        id: "2",
        mark: "C",
        content: "饼干、面包、乳饮料",
        score: "3",
      },
      {
        id: "3",
        mark: "D",
        content: "粥、面饼、包子、奶、鸡蛋",
        score: "4",
      },
      {
        id: "4",
        mark: "E",
        content: "粥、面饼、包子、奶、鸡蛋、蔬菜、水果、坚果",
        score: "5",
      },
    ],
  },
  {
    id: "4",
    range: [0, 2],
    name: "您是否愿意学校开设营养早餐供应，技能节约休息时间，又能保证孩子的早餐营养？",
    answer: [
      {
        id: "0",
        mark: "A",
        content: "愿意",
        score: "1",
      },
      {
        id: "1",
        mark: "B",
        content: "不愿意",
        score: "",
      },
    ],
  },
];
